version: '3.8'

services:
  guitarshopapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guitarshopapi
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
      - redis
    environment:
      # Database SQL SERVER
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=guitarshopangulardb;User=myuser;Password=YourStrong!Password;"
      
      # Redis
      RedisConnection__Host: "redis"
      RedisConnection__Port: "6379"
      RedisConnection__User: "default"
      RedisConnection__Password: ""

      # Stripe
      # StripeSettings__PublishableKey": ""
      # StripeSettings__SecretKey": ""
      # StripeSettings__WhSecret": ""
      
      # Enable Swagger
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - guitarshop-network

  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   container_name: sqlserver
  #   environment:
  #     SA_PASSWORD: "YourStrong!Password"
  #     ACCEPT_EULA: "Y"
  #   ports:
  #     - "1433:1433"
  #   networks:
  #     - guitarshop-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: "guitarshopangulardb"
      MYSQL_USER: "myuser"
      MYSQL_ROOT_PASSWORD: "YourStrong!Password"
      MYSQL_PASSWORD: "YourStrong!Password"
    ports:
      - "3316:3316"
    volumes:
      - ./MysqlScript/volume-mysql:/var/lib/mysql
     #- ./MysqlScript/initial_script.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    networks:
      - guitarshop-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - guitarshop-network

networks:
  guitarshop-network:
    driver: bridge
